package beans.management.system.GUI;

import beans.management.system.Model.User;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utils.SessionManager;

/**
 *
 * @author malee
 */
public class EmployeeDashboardFrame extends javax.swing.JFrame {
    
    private java.awt.CardLayout cardLayout;

    /**
     * Creates new form ManagerDashboardFrame
     */
    public EmployeeDashboardFrame() {
        initComponents();
        cardLayout = new java.awt.CardLayout();
        contentPanel.setLayout(cardLayout);
        loadForm(new CreatePromotion());
        
        // Check if user is logged in, otherwise redirect to login screen
        if (!SessionManager.isLoggedIn()) {
            JOptionPane.showMessageDialog(this, "You must log in first.");
            new LoginFrame().setVisible(true);
            this.dispose(); // Close the current frame
            return;
        }

        // Get the current user session
        User currentUser = SessionManager.getCurrentUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        viewSalesReportsButton = new javax.swing.JButton();
        ordersButton = new javax.swing.JButton();
        categorieButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        itemButton = new javax.swing.JButton();
        inventoryButton = new javax.swing.JButton();
        customerButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        navPanel.setBackground(new java.awt.Color(253, 247, 242));
        navPanel.setPreferredSize(new java.awt.Dimension(180, 500));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cafe_logo_150x150.png"))); // NOI18N
        logo.setName(""); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(100, 100));

        viewSalesReportsButton.setBackground(new java.awt.Color(77, 46, 10));
        viewSalesReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewSalesReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        viewSalesReportsButton.setText("View Sales Reports");
        viewSalesReportsButton.setMaximumSize(new java.awt.Dimension(160, 35));
        viewSalesReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalesReportsButtonActionPerformed(evt);
            }
        });

        ordersButton.setBackground(new java.awt.Color(77, 46, 10));
        ordersButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ordersButton.setForeground(new java.awt.Color(255, 255, 255));
        ordersButton.setText("Orders");
        ordersButton.setMaximumSize(new java.awt.Dimension(160, 35));
        ordersButton.setPreferredSize(new java.awt.Dimension(100, 27));
        ordersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersButtonActionPerformed(evt);
            }
        });

        categorieButton.setBackground(new java.awt.Color(77, 46, 10));
        categorieButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        categorieButton.setForeground(new java.awt.Color(255, 255, 255));
        categorieButton.setText("Categories");
        categorieButton.setMaximumSize(new java.awt.Dimension(160, 35));
        categorieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorieButtonActionPerformed(evt);
            }
        });

        logOutButton.setBackground(new java.awt.Color(77, 46, 10));
        logOutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("Log Out");
        logOutButton.setMaximumSize(new java.awt.Dimension(160, 35));
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        itemButton.setBackground(new java.awt.Color(77, 46, 10));
        itemButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemButton.setForeground(new java.awt.Color(255, 255, 255));
        itemButton.setText("Items");
        itemButton.setMaximumSize(new java.awt.Dimension(160, 35));
        itemButton.setPreferredSize(new java.awt.Dimension(100, 27));
        itemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemButtonActionPerformed(evt);
            }
        });

        inventoryButton.setBackground(new java.awt.Color(77, 46, 10));
        inventoryButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inventoryButton.setForeground(new java.awt.Color(255, 255, 255));
        inventoryButton.setText("Inventory");
        inventoryButton.setMaximumSize(new java.awt.Dimension(160, 35));
        inventoryButton.setPreferredSize(new java.awt.Dimension(100, 27));
        inventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryButtonActionPerformed(evt);
            }
        });

        customerButton.setBackground(new java.awt.Color(77, 46, 10));
        customerButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerButton.setForeground(new java.awt.Color(255, 255, 255));
        customerButton.setText("Customer");
        customerButton.setMaximumSize(new java.awt.Dimension(160, 35));
        customerButton.setPreferredSize(new java.awt.Dimension(100, 27));
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewSalesReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(categorieButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ordersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(186, 186, 186))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSalesReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ordersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(categorieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(navPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadForm(JPanel formPanel) {
        contentPanel.removeAll();  // Remove the current form
        contentPanel.add(formPanel);  // Add the new form to the content panel
        cardLayout.show(contentPanel, "form");  // Show the new form in the content panel
        revalidate();
        repaint();
    }
   

    private void viewSalesReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalesReportsButtonActionPerformed
        loadForm(new ViewSalesReports());
    }//GEN-LAST:event_viewSalesReportsButtonActionPerformed

    private void categorieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorieButtonActionPerformed
        loadForm(new ManageCategories());
    }//GEN-LAST:event_categorieButtonActionPerformed

    private void ordersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersButtonActionPerformed
        loadForm(new ManageEmployees());
    }//GEN-LAST:event_ordersButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // Clear the session and redirect to login screen
        SessionManager.logout();
        JOptionPane.showMessageDialog(this, "You have been logged out.");
        new LoginFrame().setVisible(true);  // Show login screen
        this.dispose();  // Close the current frame (ManagerDashboardFrame)
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void itemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemButtonActionPerformed
        loadForm(new ManageItems());
    }//GEN-LAST:event_itemButtonActionPerformed

    private void inventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryButtonActionPerformed
        loadForm(new ManageInventory());
    }//GEN-LAST:event_inventoryButtonActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton categorieButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton customerButton;
    private javax.swing.JButton inventoryButton;
    private javax.swing.JButton itemButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel navPanel;
    private javax.swing.JButton ordersButton;
    private javax.swing.JButton viewSalesReportsButton;
    // End of variables declaration//GEN-END:variables
}
