/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package beans.management.system.GUI;

import beans.management.system.Model.User;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utils.SessionManager;

/**
 *
 * @author malee
 */
public class ManagerDashboardFrame extends javax.swing.JFrame {
    
    private java.awt.CardLayout cardLayout;

    /**
     * Creates new form ManagerDashboardFrame
     */
    public ManagerDashboardFrame() {
        initComponents();
        cardLayout = new java.awt.CardLayout();
        contentPanel.setLayout(cardLayout);
        loadForm(new ViewSalesReports());
        
        // Check if user is logged in, otherwise redirect to login screen
        if (!SessionManager.isLoggedIn()) {
            JOptionPane.showMessageDialog(this, "You must log in first.");
            new LoginFrame().setVisible(true);
            this.dispose(); // Close the current frame
            return;
        }

        // Get the current user session
        User currentUser = SessionManager.getCurrentUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        viewSalesReportsButton = new javax.swing.JButton();
        manageEmployeesButton = new javax.swing.JButton();
        promotionButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        navPanel.setBackground(new java.awt.Color(253, 247, 242));
        navPanel.setPreferredSize(new java.awt.Dimension(180, 500));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cafe_logo_150x150.png"))); // NOI18N
        logo.setName(""); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(100, 100));

        viewSalesReportsButton.setBackground(new java.awt.Color(77, 46, 10));
        viewSalesReportsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewSalesReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        viewSalesReportsButton.setText("View Sales Reports");
        viewSalesReportsButton.setMaximumSize(new java.awt.Dimension(160, 35));
        viewSalesReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalesReportsButtonActionPerformed(evt);
            }
        });

        manageEmployeesButton.setBackground(new java.awt.Color(77, 46, 10));
        manageEmployeesButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageEmployeesButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEmployeesButton.setText("Manage Employees");
        manageEmployeesButton.setMaximumSize(new java.awt.Dimension(160, 35));
        manageEmployeesButton.setPreferredSize(new java.awt.Dimension(100, 27));
        manageEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeesButtonActionPerformed(evt);
            }
        });

        promotionButton.setBackground(new java.awt.Color(77, 46, 10));
        promotionButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        promotionButton.setForeground(new java.awt.Color(255, 255, 255));
        promotionButton.setText("Manage Promotions");
        promotionButton.setMaximumSize(new java.awt.Dimension(160, 35));
        promotionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promotionButtonActionPerformed(evt);
            }
        });

        logOutButton.setBackground(new java.awt.Color(77, 46, 10));
        logOutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("Log Out");
        logOutButton.setMaximumSize(new java.awt.Dimension(160, 35));
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewSalesReportsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(promotionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageEmployeesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(186, 186, 186))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSalesReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageEmployeesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(promotionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(navPanel, java.awt.BorderLayout.LINE_START);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadForm(JPanel formPanel) {
        contentPanel.removeAll();  // Remove the current form
        contentPanel.add(formPanel);  // Add the new form to the content panel
        cardLayout.show(contentPanel, "form");  // Show the new form in the content panel
        revalidate();
        repaint();
    }
   

    private void viewSalesReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalesReportsButtonActionPerformed
        loadForm(new ViewSalesReports());
    }//GEN-LAST:event_viewSalesReportsButtonActionPerformed

    private void promotionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promotionButtonActionPerformed
        loadForm(new ManagePromotions());
    }//GEN-LAST:event_promotionButtonActionPerformed

    private void manageEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeesButtonActionPerformed
        loadForm(new ManageEmployees());
    }//GEN-LAST:event_manageEmployeesButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // Clear the session and redirect to login screen
        SessionManager.logout();
        JOptionPane.showMessageDialog(this, "You have been logged out.");
        new LoginFrame().setVisible(true);  // Show login screen
        this.dispose();  // Close the current frame (ManagerDashboardFrame)
    }//GEN-LAST:event_logOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerDashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel logo;
    private javax.swing.JButton manageEmployeesButton;
    private javax.swing.JPanel navPanel;
    private javax.swing.JButton promotionButton;
    private javax.swing.JButton viewSalesReportsButton;
    // End of variables declaration//GEN-END:variables
}
